### ISSUE TITLE
Value::operator[] should accept std::size_t

### ISSUE THREAD

**Issue by yumetodo** [jefftimesten/ofxJSON#22]
https://github.com/jefftimesten/ofxJSON/blob/5934d7044406041d46c763d0509613ac71801256/libs/jsoncpp/include/json/json.h#L657
There are 2 overload that accept

- ``int``
- ``ArrayIndex``

According to line 236,
https://github.com/jefftimesten/ofxJSON/blob/5934d7044406041d46c763d0509613ac71801256/libs/jsoncpp/include/json/json.h#L236

```cpp
typedef unsigned int ArrayIndex;
```

``ArrayIndex`` is ``unsigned int``.

Now, I'm tried to pass ``std::size_t`` value but failed.
https://travis-ci.org/Lacty/ToTheTop/builds/195512607
Because gcc defines ``std::size_t`` as ``unsigned long``

According to C standerd, ``unsigned long`` is bigger or same with ``unsigned int``. So, overload resolution was failed.

Why don't you accept ``std::size_t``?
All of ``operator[]`` defined at STL container can accept ``std::size_t``.

There are two scenarios to solve that.

1. ``typedef std::size_t ArrayIndex;``(breaking change!)
2. Add overload for ``std::size_t``(Note: SFINAE is required to avoid conflict with ``Json::ArrayIndex``. ex.) http://melpon.org/wandbox/permlink/V24WVUhGMvc7SjQH)

**Comment by bakercp** [comment]
This is an issue for the upstream https://github.com/open-source-parsers/jsoncpp library, rather than an issue for this wrapper ofx addon.

Perhaps it is already solved upstream?  If so, perhaps we could incorporate the newer version into the addon?

**Comment by bakercp** [comment]
It looks like it is the same upstream: 

https://github.com/open-source-parsers/jsoncpp/blob/b063cf4adaacaf68b0e8aa69aef637d6052accbb/include/json/forwards.h#L26

Here is a discussion of related issues:

https://github.com/open-source-parsers/jsoncpp/search?l=Text&q=arrayindex&type=Issues&utf8=%E2%9C%93


Here is a workaround:

https://github.com/open-source-parsers/jsoncpp/issues/541

Closing this issue.

**Comment by bakercp** [comment]
Also, in the latest version of openFrameworks, `ofJson` is now a core class.

**Comment by yumetodo** [comment]
@bakercp Thank you for your investigation.
I'll check upstream code and openFrameworks core code.
