### ISSUE TITLE
JSON Parsing. Does not like some characters in filename (will not load)

### ISSUE THREAD

**Issue by danoli3** [jefftimesten/ofxJSON#7]
I've been experiencing some strange issues with my JSON parsing.

So if a file I have is named:
```example.1.json``` does not load.
```example-1.json``` does not load.
```example1.json``` loads fine.
Any ideas?

This may be an issue with ofBuffer.

**Comment by bakercp** [comment]
Hey @danoli3 did you get this resolved?

**Comment by bakercp** [comment]
I'm closing this for now.  Please reopen if you still have the problem and determine it's a ofxJSON problem.  Thanks!
